server:
  port: 10086 # eureka端口
spring:
  application:
    name: eurekaserver # eureka 服务名称
#  cloud:
#    nacos:
#      server-addr: localhost:8848  # nacos服务端地址
eureka:
  client:
    service-url: # eureka 地址信息
      defaultZone: http://localhost:10086/eureka/
